### ISSUE TITLE
Difficulties accessing the deployed app

### ISSUE THREAD

**Issue by alexkolo** [nathadriele/biophenotype-rag#1]
Looks like a cool project, unfortunately I can't access the deployed version to try it:

![image](https://github.com/user-attachments/assets/662c7b76-d1e7-4c2c-82ec-7cb84750793a)

**Comment by nathadriele** [comment]
Hello, @alexkolo!

Please try again: https://dry-recipe-9383.ploomberapp.io.

![image](https://github.com/user-attachments/assets/7b6cdd17-1c9c-4eae-bf94-b5c6b5afaebf)


Thank you for your feedback.

**Comment by alexkolo** [comment]
Can confirm. Works again. Thx
