### ISSUE TITLE
Unable to run the application - missing key instruction on how to run

### ISSUE THREAD

**Issue by dusisarathchandra** [nathadriele/biophenotype-rag#2]
Hi @nathadriele 

I see the code is well structured, and I find the use case interesting. Although most of the information is captured, some of the instructions are missing which is making it difficult for me to review. Would like you to update with latest changes so that I can take a new dump of the code and retry once. Thank you for understanding.

**Comment by nathadriele** [comment]
Thank you for your considerations, @dusisarathchandra.
